### ISSUE TITLE
Add the ability to execute 'zarf package deploy' to deploy a zarf package to a Kubernetes cluster

### ISSUE THREAD

**Issue by lucasrod16** [defenseunicorns/setup-zarf#38]
Relates to https://github.com/defenseunicorns/setup-zarf/issues/35

Users would like the ability for this action to do the following:
- Deploy a zarf package (zarf package deploy) to a Kubernetes cluster

Acceptance criteria:
- test(s) in place that verify the behavior of the logic
- CI has validated the changes and is passing ✅

**Comment by jeff-mccoy** [comment]
Not sure how this will add value as you'd be writing tightly-coupled custom logic to avoid running `zarf package deploy <name>`, if this were an action you'd still need this, but in a non-portable form:

```yaml
uses: defenseunicorns/setup-zarf@main
with:
  version: <version> # Required
  download-init-package: true
  deploy-package: <name>
```
